### ISSUE TITLE
Deprecation warning using ActiveRecord 5.2

### ISSUE THREAD

**Issue by tomhughes** [feedreader/pluto#14]
When using ActiveRecord 5.2.x deprecation warnings are issued:

```
DEPRECATION WARNING: Dangerous query method (method whose arguments are used as raw SQL) called with non-attribute argument(s): "coalesce(items.updated,items.published,'1971-01-01') desc". Non-attribute arguments will be disallowed in Rails 6.0. This method should not be called with user-provided values, such as request parameters or model attributes. Known-safe values can be passed by wrapping them in Arel.sql(). (called from make_for at (erb):12)
```

**Comment by geraldb** [comment]
@tomhughes  Happy new year! Prosit 2019! Thanks for reporting the deprecation warning for the SQL query.  If will try to look into the required change for a safe alternative. Thanks. Cheers. Prost.

**Comment by hellcp** [comment]
With newer ActiveRecord the amount of the deprecation warnings is growing:
```
DEPRECATION WARNING: Setting `ActiveRecord::Base.configurations` with `[]=` is deprecated. Use `ActiveRecord::Base.configurations=` directly to set the configurations instead.
```

**Comment by geraldb** [comment]
@hellcp Thanks for reporting more deprecation warnings. I will try to have a look in 2020 for sure now. Prosit 2020! Happy new year! Cheers.

**Comment by geraldb** [comment]
@hellcp Thanks for the patches and fixes. Merged.  I will try to push out new gems in the next days. PS: The issue got auto-closed somehow by github magic. I keep it open until the new gems are pushed / published.

**Comment by geraldb** [comment]
Thanks again to @hellcp for the patches.  I have updated / pushed / published all gems with new version incl. the top-level pluto, that is, now at version 1.3.2.  Note: I also updated the ruby version to match the ActiveRecord 5.2+ minimum, that is, Ruby 2.2.2+.    Please, update the pluto gems and if you still find any deprecating warnings, please report back. Thanks again. Prosit 2020! Cheers.
