### ISSUE TITLE
won't build page for ini configuration with dash / non a-z characters in name e.g. aries-rfcs

### ISSUE THREAD

**Issue by infominer33** [feedreader/pluto#28]
I'm using [rss-bridge](https://github.com/RSS-Bridge/rss-bridge/) to generate a feed of github issues+comments.. I tried both [ATOM](https://infominer.id/pluto-planet-demo/aries-rfcs-comments.xml) and [Mrss](https://infominer.id/pluto-planet-demo/aries-rfcs-c.xml).

I also tried in other feed readers to be sure, and was able to get feedly and LuckNews both to recognize these feeds.

here's a [paste of my output](https://pastebin.com/embed_iframe/WZyVAPrg)

**Comment by geraldb** [comment]
I would say the trouble is not with the feed itself but your name of the configuration .ini file  e.g. aries-rfcs.ini.
The error / warning on generation issued is : *** warn: no site with key 'aries-rfcs' found; using untitled site record

The easiest fix for now is to use a configuration name without dash e.g. try  ariesrfcs.ini or something similar.

**Comment by infominer33** [comment]
brilliant! thanks again!

**Comment by geraldb** [comment]
Note: I'm just assuming from the log output. I haven't tried if it works for sure. Please, report back if it doesn't work with the new name (with just a-z letters).
