### ISSUE TITLE
build without feedcheck?

### ISSUE THREAD

**Issue by infominer33** [feedreader/pluto#30]
How do I build from the db without checking feeds, while tinkering with the templates?
(just assuming this is possible, but still working understand how the various parts of this project fit together)
-thx

**Comment by geraldb** [comment]
That's more of a (support) question than a bug report :-)  and ideally better posted in the community forum <http://groups.google.com/group/wwwmkae>.   You can use $ pluto merge  for building (merging) templates from the db without feed checks. See the quick starter F.A.Q docu <https://github.com/feedreader/pluto.starter#questions-n-answers>.

**Comment by infominer33** [comment]
ok, thanks.. I'll remember that and use the forum next time...

I've really wondered what that merge command did, that would have been my next question!

**Comment by geraldb** [comment]
No worries.  Yeah sorry - merging templates that's the technical term that is merging the data with the templates - I think it started with Microsoft Word / Office and the "mail merge", see <https://docs.microsoft.com/en-us/power-platform/admin/work-mail-merge-templates>
