### ISSUE TITLE
error: SSL_connect

### ISSUE THREAD

**Issue by infominer33** [feedreader/pluto#31]
doesn't happen every time... but this is the second time it happened today. so I figured it was worth reporting here.

```
[info] found cache entry for >https://glia.net/the-blog?format=rss<
[info] adding header If-None-Match (etag) >W/"0fc4cbe2e2ab08cd539e871f3f48f9d2"< for conditional GET


*** error: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3/TLS write client hello

##[error]Process completed with exit code 1.
```

**Comment by geraldb** [comment]
Thanks for reporting the SSL / HTTPS connection errror.

**Comment by infominer33** [comment]
I guess the problem is, not so much the connection error, as the build failing because of that connection error.

**Comment by geraldb** [comment]
I see - good point - I try to add the error to the list of "recovered" catched errors that get logged but processing (on the next feed) continues.  The rescue line is here <https://github.com/feedreader/pluto/blob/master/pluto-feedfetcher/lib/pluto/feedfetcher/cond_get_with_cache.rb#L42>.
