### ISSUE TITLE
TypeError: no implicit conversion of String into Integer

### ISSUE THREAD

**Issue by infominer33** [feedreader/pluto#32]
Trying to build\run this app directly, rather than just installed gem.

1. Fork repository.
2. `cd pluto/pluto-merge' (or `pluto/pluto`)
3. `gem install hoe`
4. `rake init --trace`
```
rake aborted!
TypeError: no implicit conversion of String into Integer
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hoe-3.22.1/lib/hoe.rb:528:in `[]'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hoe-3.22.1/lib/hoe.rb:528:in `block in define_spec'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/specification.rb:2008:in `initialize'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hoe-3.22.1/lib/hoe.rb:512:in `new'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hoe-3.22.1/lib/hoe.rb:512:in `define_spec'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hoe-3.22.1/lib/hoe.rb:815:in `post_initialize'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/hoe-3.22.1/lib/hoe.rb:394:in `spec'
/Users/infominer/jamstack/plutoplanet/pluto/pluto-merge/Rakefile:4:in `<top (required)>'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:703:in `raw_load_rakefile'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:104:in `block in load_rakefile'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:103:in `load_rakefile'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:82:in `block in run'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:80:in `run'
/Users/infominer/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/Users/infominer/.rbenv/versions/2.7.0/bin/rake:23:in `load'
/Users/infominer/.rbenv/versions/2.7.0/bin/rake:23:in `<main>'
```
I spent a lot of time digging around the code and trying different things, but didn't get very far.

Ultimately, I'm trying to require an additional dependency (nokogiri) to use in my template.. hopefully I'm at least pointed in the right general direction :)

**Comment by geraldb** [comment]
That looks like a hoe rake task erros.   See  <https://yukimotopress.github.io/gem-tasks> for hoe.    What is:

    $ rake init

trying to do?  Do you have a Rakefile?  If you want to use nokogiri in your template, add at the top:

    <% require 'nokogiri' %>

Not sure why you need hoe - Hoe itself is for BUILDING / PUBLISHING new gems and not really for USING gems.

**Comment by infominer33** [comment]
oh haha :sweat_smile: I really didn't think it could be that simple! 

There are rakefiles in folders of the various components of pluto.. and I used `rake init` on the plutolive.starter ... 

I'm getting familiar with the different aspects, and reading a bunch online while I poke around... but not quite grasping how all the parts fit together, quite yet. 

I assumed if I wanted to add a dependency to the merge function I'd have to build it custom.

**Comment by geraldb** [comment]
ERB (Embedded RuBy) in the templates is just regular plain vanilla ruby.  You can also include your own script with require or require_relative e.g. use:
     <% require './myscript' %>  

And in myscript.rb you can require nokogiri and add your own scripts for use in the templates.
