### ISSUE TITLE
Confusing fetched vs updated_at

### ISSUE THREAD

**Issue by thatnerdjosh** [feedreader/pluto#38]
In https://feedreader.github.io/#create-your-own-templates---template-reference, it says:

```
<TMPL_VAR date>                |  <%= site.fetched %>     # site (planet) last updated
```

While I am a Ruby novice, after a few hours I managed to get everything running locally and dove into the code a bit to figure out what `Site.fetched` does. It seems if I am understanding correctly that `SiteFetcher` has the feature to load an INI of feeds dynamically. Furthermore, it seems that IFF the below is true the `fetched` attribute will be updated:

1. `url` is set in `site` config and points to a URL which contains text (being in INI format)
2. `rake update-sites` from `update.rake` in `pluto-rake` is used

Additionally, I notice that in https://github.com/planet-templates/planet-blank/blob/master/blank.cards.html.erb#L39, `updated_at` is used instead of `fetched`.

Is it the correct use-case to use `updated_at`, and is my understanding of how this works correct? If so, I think the docs in the first link of this issue will need updated.

Thanks ahead of time.

**Comment by geraldb** [comment]
Sorry for the confusion about date.  If you do not know what date to use there is now a date called date :-), that is, if you do not care (fetched/created/updated/etc) use site.date.

fetched - is the date when pluto fetches (HTTP get) / downloads the feed

**Comment by thatnerdjosh** [comment]
Hello @geraldb, yes I understand that and it makes great sense (and works fine) for feeds.

My question still stands:

1. What is fetched in the context of site? Not in the context of feed.
2. Why does the CLI not update site fetched over the build, update, or fetch commands?
3. The only place I have seen which makes use of fetched at site level is the update.rake task; and it is fetching the site URL
  3a. What is site URL used for (as opposed to feed URL)

Thanks.

**Comment by geraldb** [comment]
Q: What is fetched in the context of site? Not in the context of feed.

The idea of site.fetched and site.url is / was as far as I can remember for the planet.ini configuration file and as far as I can remember that was used for the online version(s) using the  SiteRefresher that is no longer in use for the command line version.
