### ISSUE TITLE
The -q/--quiet option doesn't seem to work

### ISSUE THREAD

**Issue by tomhughes** [feedreader/pluto#4]
According to the CLI help:

```
    -q, --quiet       - Only show warnings, errors and fatal messages
```

but as far as I can see it makes no difference, and indeed the command argument handling doesn't even seem to look for that flag?

**Comment by geraldb** [comment]
@tomhughes   Thanks for reporting. Yes, sorry for now "everything" gets output to the console.

However, if you want to check up on errors with feeds or your activity log - than everything gets stored in the sqlite database. See the activity table (will try to make the pluto.admin web app into a command line tool in the next weeks). See an example here -> http://planetruby.herokuapp.com/db/time

As an alternative if interested you can add an extra page / template (e.g. log or timeline) to your template pack that prints / generates the activity to your pages. (If interested I can try it and send you the sample page as gist (or a pull request if preferred). Again thanks for using pluto (if anything else comes up, please just let me know. Great to see / get some thoughts / changes from a live site/planet.) Cheers.

**Comment by geraldb** [comment]
Thanks for @harry-wood for the work on starting with the --quiet and --quieter options.  It's all working and already published in the pluto gems.  I'm closing the ticket / issue if there is still something printed with the --quiet/--quieter option, please report back. Cheers. Prosit 2020!
