### ISSUE TITLE
DEPRECATION WARNING: to_h is deprecated and will be removed from Rails 7.0

### ISSUE THREAD

**Issue by bmos** [feedreader/pluto#44]
I'm getting this notice in the log. Other than seeing it, there is no issue.

``DEPRECATION WARNING: to_h is deprecated and will be removed from Rails 7.0 (You can use `ActiveRecord::Base.configurations.configs_for(env_name: 'env', name: 'primary').configuration_hash` to get the configuration hashes.) (called from load at /home/.../ruby/3.2.0/bin/pluto:25)``

**Comment by bmos** [comment]
This seems like a new iteration of #42

**Comment by geraldb** [comment]
@bmos thanks for finding out more. time to update. i try my best. thks for trying / using pluto.
