### ISSUE TITLE
[RFE] Export collected feeds as new atom/rss feed?

### ISSUE THREAD

**Issue by liquidat** [feedreader/pluto#9]
Hi, is there a way to export all collected feeds as a new, combined feed?

The reason for the request is: I am used to access planet pages (planet Fedora, planet Gnome, etc.) and subscribe to the available, combined feeds of these planets. I want to offer this on my planets as well.

Any chance of making this possible as an option or in the template?

**Comment by geraldb** [comment]
@liquidat  If I dare to say it's easy. Do-it-yourself (DIY) :-)   Add a new feed.xml template to your theme pack. That's it. See the [rss.xml.erb example from Open Street Map Blogs/Planet](https://github.com/gravitystorm/blogs.osm.org/blob/master/theme/rss.xml.erb) or copy one of the feeds example from [/planet-feeds](https://github.com/planet-templates/planet-feeds) into your template folder (and change to your needs). Let me know how it goes. If you publish your theme pack/templates/setup happy to contribute if needed. Keep it up. Cheers. Greetings from Vienna.

**Comment by liquidat** [comment]
Thanks very much, that really helps and seems to work. Great! =)
